### ISSUE TITLE
Upload through a secure connection.

### ISSUE THREAD

**Issue by sauron** [nicksieger/multipart-post#18]
Hello,

I'm trying to use this gem to upload files through a secure connection using SSL, but it seems to be impossible.

Does anyone have a guide or something to help me sort this issue?

I've tried some combinations of the code using http://www.rubyinside.com/nethttp-cheat-sheet-2940.html
but no luck.

Thanks.

**Comment by retorquere** [comment]
When I do the above (sans the verify_node), I get "IOError: use_ssl value changed, but session already started"

**Comment by MaxPleaner** [comment]
Seconding @retorquere 

I did not want to use `OpenSSL::SSL::VERIFY_NONE` because I'm using multipart post in a test suite and it is important to verify the SSL connection. 

I also got the IOError. The backtrace:

```txt
[2] pry(#<RSpec::ExampleGroups::PerformanceTest>)> e.backtrace
=> ["/home/max/.rbenv/versions/2.4.0-dev/lib/ruby/2.4.0/net/http.rb:758:in `use_ssl='",
 "/home/max/Desktop/timeset-backend/backend/spec/test_helpers.rb:779:in `block (2 levels) in multipart_post'",
 "/home/max/.rbenv/versions/2.4.0-dev/lib/ruby/2.4.0/net/http.rb:853:in `start'",
 "/home/max/.rbenv/versions/2.4.0-dev/lib/ruby/2.4.0/net/http.rb:584:in `start'",
 "/home/max/Desktop/timeset-backend/backend/spec/test_helpers.rb:778:in `block in multipart_post'",
 "/home/max/Desktop/timeset-backend/backend/spec/test_helpers.rb:773:in `open'",
 "/home/max/Desktop/timeset-backend/backend/spec/test_helpers.rb:773:in `multipart_post'",
 "/home/max/Desktop/timeset-backend/backend/spec/test_helpers.rb:661:in `create_raw_photo'",
 "/home/max/Desktop/timeset-backend/backend/spec/performance_spec.rb:53:in `block (3 levels) in init_database'",
 "/home/max/Desktop/timeset-backend/backend/spec/performance_spec.rb:53:in `times'",
:
........ ETCETERA

```

**Comment by MaxPleaner** [comment]
never mind, I figured out how to do this. I had to split out my `Net::HTTP.start` call into two ... first `my_req = Net::HTTP.new`, then `my_req.start`. In between these two I added the `use_ssl` option.
I did *not* have to use the `OpenSSL::SSL::VERIFY_NONE` option. Thanks to the gem creators for the helpful software by the way.
