### ISSUE TITLE
Can't debug an http result

### ISSUE THREAD

**Issue by dbrouard** [nicksieger/multipart-post#41]
Hi, first of all thanks for this gem.

I'm trying to make it work but I don't see the uploaded file at my server. It may be related to several things, and, in order to debug, I wanted to see the request information, for example whether it's a 404 not found or a 403 not allowed.

When I do this: puts "Result: #{res}", nothing is echoed. Is there anyway to debug the result of a request.

Thanks, Diego.

**Comment by pavel-jurasek-merck-com** [comment]
@dbrouard i would say you should setup debug on HTTP library what you use ... for instance:

http = Net::HTTP.new(uri.host, uri.port)
http.set_debug_output($stdout)

**Comment by ioquatix** [comment]
I'm adding this to the README - thanks so much @pavel-jurasek-bcgdv-com
